<?php

/**
 * Implements hook_help().
 *
 * Provides a help page description for the module.
 */
function etss2_payment_icons_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.etss2_payment_icons_help':
      return t('This module provides a custom block for adding and managing payment gateway icons.');
  }
}

/**
 * Implements hook_block_info().
 *
 * Defines the block that displays payment gateway icons.
 */
function etss2_payment_icons_block_info() {
  return [
    'etss2_block_payment_icons' => [
      'info' => t('ETSS2 Payment Gateway Icons Block'),
      'description' => t('Displays payment gateway icons uploaded by the user.'),
    ],
  ];
}


/**
 * Implements hook_theme().
 */
function etss2_payment_icons_theme()
{
  return [
    'etss2_payment_icons' => [
      'template' => 'etss2_payment_icons', 
      'variables' => ['icons' => NULL], 
    ],
  ];
}