etss2_theme_settings.admin:
  title: 'ETSS2 Theme Settings'
  description: 'Manage Theme Settings for ETSS2.'
  parent: system.admin_config_system
  route_name: etss2_theme_settings.form
  weight: 200
  menu_name: admin
